### ISSUE TITLE
INCOMPATIBLE WITH WINDOWS 10

### ISSUE THREAD

**Issue by Patrik356b** [Patrik356b/addfwrs_auto#1]
Due to a change/bug in the cmd API this script get's the wrong path returned and thus starts to block EVERYTHING matching windows/system32/*.exe

**Comment by charlesdh** [comment]
Hi Patrik,

I'm not certain what you're referring to.  If you explain in more detail I will investigate.

It sounds like you haven't navigated to the correct path before running addfwrs.  Could this be the case?

Regards
Charles

**Comment by Patrik356b** [comment]
It does work on windows 7 and windows 8.

I think the API broke or changed in windows 10 but i haven't looked into it.

**Comment by charlesdh** [comment]
There is no API calls.  It's all command line scripting.

It's tried and tested in Windows 10.  It works flawlessly.  I can only suggest you're not changing your directory before running the file.  You MUST be in the root folder of the application install for it to work (i,e in c:\program files\my program\ ) or whatever other untrustworthy application folder you want to deny access to the internet.

You cannot run the program from c:\windows\system32\ for instance.  You must change directory to the app folder first.

If this still doesn't work for you - please send screen prints and I'll help you as best I can.

Thanks,
Charles

**Comment by Patrik356b** [comment]
I will send screenshot later, but it never retrieved the current path hence
windows/system32 was used.
(maybe win10 upgrade broke cmd a bit)

Also: I never ran this script from anything else than the root of the
program I wanted to block.
Though if the script is run in a folder without any exe files, nothing
should happen.

**Comment by charlesdh** [comment]
Hi,

It will block both .exe and .dll files by default.  What location did you install the addfwrs.bat file to? 

For it to work properly,

1) You need to be running cmd as Administrator
2) You need to have the folder that you installed addfwrs.bat set in your paths (i.e: add in set path)
2) You need to be in the root folder of the program you want to block.
3) You need to give it a name for the rules, so for instance from command line run: addfwrs myprog
4) Then follow actions on screen.

Screen prints will be needed if it doesn't work otherwise.  I doubt your Win 10 has been corrupted, it would be all over the news if Microsoft made some bad upgrades.  You could run Anti-virus checker to be on the safe side.

Good luck.

Regards,
Charles

**Comment by Patrik356b** [comment]
I don't think you have looked into how this version differs from yours and it seems that the paths does not work in certain folders: 
![bad path](http://puu.sh/k3Axv/c7df5455a9.png)

This sets up the rule name using the name of the current folder:
`for /f "delims=" %%A in ('cd') do (
     set RULENAME=%%~nxA
)`

**Comment by charlesdh** [comment]
Hi,

I'm guessing you want to modify the script to create the firewall rule name the same as the root folder app you're wanting to block?

1) Please provide a screen print of the command you're running to activate it.
2) If you've modified the script please attach a copy for review.
3) You might be using an old version your one doesn't block *.dlls.

Thanks.

**Comment by charlesdh** [comment]
Ah - sorry just seen your amended version.  ok will take a look.  :-)

**Comment by charlesdh** [comment]
Hi
Your code should look like below (also do you want this just to block *.exe or both *.exe & *.dll?):

@CLS
@echo off
REM    BATCH FILE CREATED BY CHARLES DE HAVILLAND 20/02/2012
REM    MODIFIED BY Patrik356b & Charles de Havilland 08/09/2015
REM   SRC: https://sites.google.com/site/mytools4000/home/allow-block-multiple-programs-through-windows-7-firewall

for %%* in (.) do set RULENAME=%%~nx*

ECHO Create in/out firewall rules for all *.exe files with the rulename of "%RULENAME%" ?
ECHO.
ECHO.
pause

Echo.
FOR /r %%G in ("*.exe") Do (@echo %%G
NETSH advfirewall firewall add rule name="%RULENAME%-%%~nxG" dir=in program="%%G" action="block" enable="yes")
FOR /r %%G in ("*.exe") Do (@echo %%G
NETSH advfirewall firewall add rule name="%RULENAME%-%%~nxG" dir=out program="%%G" action="block" enable="yes")
Echo.
Echo done.
Echo.
Echo Batch ended...
pause&exit

**Comment by charlesdh** [comment]
Hi,
You might prefer this updated version:
https://github.com/charlesdh/addfwrs

It can do both, run without a rule name, or you can add a rulename.  Does this do what you were looking for?

**Comment by Patrik356b** [comment]
Actually this has the exact same problem:
![img](http://puu.sh/k4H1y/b501d217c2.png)

I have a plugin for AutoCAD and it has a bug with it's updater, hence that one has to be blocked.
(The updater can not be turned off and it hangs because it doesn't get the requested response from a now closed website)

I suggest you try the following to create a similar scenario:
copy notepad.exe into C:\Program Files\Autodesk\AutoCAD 2015\

Then run my and your new version from this folder and compare, it should produce the same result i believe

**Comment by charlesdh** [comment]
I have tested both in the exact same scenario you mention above, and they work flawlessly on my win 10 machine.

Please send screen print(s) of how you're NAVIGATING to the PROGRAM FOLDER before running the script, and then another screen print (or same) of how you're calling the script.

Have you tried both addfwrs (without a rulename) & addfwrs autodesk (with the rulename) ?

**Comment by charlesdh** [comment]
Also, try rebooting your computer with minimal services and startup app (run msconfig) and then disable any extra security features preventing scripts from running, then try running the batch file again?

**Comment by Patrik356b** [comment]
It's something to do with the elevation of privileges as the correct path
is used if run in a non-admin mode

![img](http://puu.sh/k5aO1/31c37a464e.png)
![img](http://puu.sh/k5aPO/7d16abe948.png)

On Wed, Sep 9, 2015 at 11:55 AM, charlesdh <notifications@github.com> wrote:

> Also, try rebooting your computer with minimal services and startup app
> (run msconfig) and then disable any extra security features preventing
> scripts from running, then try running the batch file again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Patrik356b/addfwrs_auto/issues/1#issuecomment-138860495>
> .
>



-- 
Best regards; Hexile

**Comment by charlesdh** [comment]
But you've attached screen images of the results again?

As two messages ago says, " Please send screen print(s) of how you're NAVIGATING to the PROGRAM FOLDER before running the script, and then another screen print (or same) of how you're CALLING (running) the script."  Please send screen prints for these.

I don't need to see the screen prints of results again (the script after you've run it).

**Comment by Patrik356b** [comment]
![123](http://puu.sh/k5aO1/31c37a464e.png)
![245](http://puu.sh/k5aPO/7d16abe948.png)

**Comment by Patrik356b** [comment]
I do not call the script with parameters as that is supposed to be fetched automatically.

**Comment by charlesdh** [comment]
Actually I think I've worked out the issue from your screen prints.  You're double clicking the batch file straight from Windows right?  It doesn't work like that.

You need to:

a) Run CMD window (in Admin mode)
b) Navigate to the program folder (i.e: cd c:\program file\autodesk\)
c) run addfwrs

It won't work by double clicking.  Admin rights changes the default folder path to c:\windows\system32

It would be easier just to move addfwrs to c:\windows folder (which is in the DOS path)

Then whenever you want to block an app - open a cmd window - navigate to the folder, and then just type addfwrs.

I hope I've been of assistance to you, and this has answered your questions.

**Comment by Patrik356b** [comment]
That's not how  it used to work though

**Comment by charlesdh** [comment]
You do realise I'm not obligated to help you?  Your messages are very stern.

**Comment by Patrik356b** [comment]
Sorry for that, i'm having a busy week.
I can no longer produce a valid result when running this as it was intended to which is run as admin in the folder of the program that you want to be blocked. (just tested on my laptop).

Can i blame Murphy's law for this?.

**Comment by charlesdh** [comment]
There is another option - you could create a shortcut of addfwrs, and amend the startup location to the c:\program files\autodesk\ folder.  Then run that with Admin rights, and it should work the way you want it to.

**Comment by Patrik356b** [comment]
I might look into that later, though i'm not sure why this worked in the first place. Perhaps admin privileges were different in Windows 7 thus allowing it to somehow function as intended.

Thanks for taking your time though.

**Comment by charlesdh** [comment]
Hi, thanks for the thanks.  I have a solution, and will update the batch file shortly and get it over to you.

**Comment by charlesdh** [comment]
Finished - this file will do what you want it to do.

https://github.com/charlesdh/fwblock.bat

**Comment by Patrik356b** [comment]
Works great, though, if possible: it would be nice if it could be run with parameters like:
fwblock.bat exe
fwblock.bat dll skipsubfolders
and then it would be perfect ;)

**Comment by charlesdh** [comment]
I can write it, but it would extend this work for me.  There would need to be something in it for me to justify my time spent on it.

**Comment by Patrik356b** [comment]
It's just s suggestion, it's fine as-is.

On Mon, Sep 14, 2015 at 6:38 PM, charlesdh <notifications@github.com> wrote:

> I can write it, but it would extend this work for me. There would need to
> be something in it for me to justify my time spent on it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Patrik356b/addfwrs_auto/issues/1#issuecomment-140138521>
> .
>



-- 
Best regards; Hexile
